# Generated by Django 4.1.5 on 2023-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('office', models.CharField(blank=True, default='#', max_length=250)),
                ('mail', models.CharField(blank=True, default='#', max_length=250)),
                ('twitter', models.CharField(blank=True, default='#', max_length=250)),
                ('facebook', models.CharField(blank=True, default='#', max_length=250)),
                ('youtube', models.CharField(blank=True, default='#', max_length=250)),
                ('instagram', models.CharField(blank=True, default='#', max_length=250)),
                ('telegram', models.CharField(blank=True, default='#', max_length=250)),
                ('linkedin', models.CharField(blank=True, default='#', max_length=250)),
                ('tiktok', models.CharField(blank=True, default='#', max_length=250)),
            ],
        ),
    ]
