# Generated by Django 4.1.5 on 2023-05-07 22:30

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('body', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
    ]
