# Generated by Django 4.1.5 on 2023-05-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
