# Generated by Django 4.1.5 on 2023-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_events_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('body', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='PastEvent',
        ),
    ]
