# Generated by Django 4.1.5 on 2023-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_upevent_rename_event_pastevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastevent',
            name='image',
        ),
        migrations.AddField(
            model_name='pastevent',
            name='headline',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
