# Generated by Django 4.1.5 on 2023-05-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_pastevent_image_pastevent_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevent',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
