# Generated by Django 4.1.5 on 2023-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_pastevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevent',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
